importScripts(
    '../vendor/ES6-Promises/dist/promise-0.1.1.js',
    '../vendor/zlib-asm/zlib.js',
    '../src/jsziptools.js',
    '../src/utils.js',
    '../src/algorithms/adler32.js',
    '../src/algorithms/crc32.js',
    '../src/algorithms/deflate.js',
    '../src/algorithms/inflate.js',
    '../src/zlib.compress.js',
    '../src/zlib.decompress.js',
    '../src/gz.compress.js',
    '../src/gz.decompress.js',
    '../src/zip.pack.js',
    '../src/zip.unpack.js',
    'worker_body.js'
);